indent = 4
margin = 100
always_for_in = true
whitespace_typedefs = false
whitespace_ops_in_indices = false
remove_extra_newlines = true
pipe_to_function_call = false
short_to_long_function_def = true
long_to_short_function_def = true
always_use_return = true
whitespace_in_kwargs = false
annotate_untyped_fields_with_any = false
format_docstrings = true
align_assignment = true
align_struct_field = true
align_conditional = true
align_pair_arrow = true
align_matrix = true
conditional_to_if = true
normalize_line_endings = "unix"
trailing_comma = true
join_lines_based_on_source = true
indent_submodule = true
separate_kwargs_with_semicolon = true
surround_whereop_typeparameters = true
